name: Test Deploy

on:
  push:
    branches: [ "main", "pre-production", "development" ]

jobs:
  main:
    runs-on: ubuntu-latest
    environment: production
    strategy:
      matrix:
        node-version: [19.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: npm run build

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.1.1
      with:
        branch: gh-pages
        folder: build
  
  pre-production:
    runs-on: ubuntu-latest
    environment: pre-production
    strategy:
      matrix:
        node-version: [19.x]

  steps:
  - uses: actions/checkout@v3
  - name: Echo
    run: |
      echo "Running a job in the pre-production environment"

  development:
    runs-on: ubuntu-latest
    environment: development
    strategy:
      matrix:
        node-version: [19.x]

    steps:
    - uses: actions/checkout@v3
    - name: Echo
      run: |
        echo "Running a job in the development environment"